/******************************************************
Cours:   LOG121
Session: H2019
Groupe:  04
Projet: Laboratoire #3
Étudiant(e)s: Eugene Wiafe, Ian Garcia-Guerrero, Kevin Chénier, Laurent Sieu
              
              
Professeur : Ghizlane El Boussaidi
Nom du fichier: CadrePrincipale.java
Date créé: 2019-03-25
Date dern. modif. 2019-03-25
*******************************************************
Historique des modifications
*******************************************************

*******************************************************/

package Vue;

import javax.swing.*;

import Controleur.PerspectiveControleur;

public class CadrePrincipale extends JFrame {

	// Bouton pour utiliser undo
	private JButton undo1;
	private JButton undo2;
	
	// Label qui designe l'image principale 
	private JLabel nameMainImage;

	private JPanel panneauPrincipal;

	private Onglet mainImage;
	private Onglet rightPersceptive;
	private Onglet leftPersceptive;

	private PerspectiveControleur perspectiveController;

	/**
	 * Creates new form NewJFrame
	 */
	public CadrePrincipale() {
		perspectiveController = new PerspectiveControleur();
		initComponents();
		this.setJMenuBar(new MenuVue());
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * Le code ci-dessous est genere par NetBeans
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		panneauPrincipal = new JPanel();
		undo1 = new JButton();
		undo2 = new JButton();
		
		nameMainImage = new JLabel();

		mainImage = new Onglet(0, perspectiveController);
		rightPersceptive = new Onglet(1, perspectiveController);
		leftPersceptive = new Onglet(2, perspectiveController);

		GroupLayout jPanel1Layout = new GroupLayout(panneauPrincipal);
		panneauPrincipal.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 100, Short.MAX_VALUE));

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		undo1.setText("Undo1");
		undo1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				undo1ActionPerformed(evt);
			}
		});

		undo2.setText("Undo2");
		undo2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				undo2ActionPerformed(evt);
			}
		});

		rightPersceptive.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		rightPersceptive.setPreferredSize(new java.awt.Dimension(225, 225));

		GroupLayout jPanel2Layout = new GroupLayout(rightPersceptive);
		rightPersceptive.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 223, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 223, Short.MAX_VALUE));

		mainImage.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		mainImage.setPreferredSize(new java.awt.Dimension(225, 225));

		GroupLayout jPanel3Layout = new GroupLayout(mainImage);
		mainImage.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 223, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 223, Short.MAX_VALUE));

		leftPersceptive.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		leftPersceptive.setPreferredSize(new java.awt.Dimension(225, 225));

		GroupLayout jPanel4Layout = new GroupLayout(leftPersceptive);
		leftPersceptive.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 223, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 223, Short.MAX_VALUE));

		nameMainImage.setHorizontalAlignment(SwingConstants.CENTER);
		nameMainImage.setText("Image Principale");

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(117, 117, 117).addComponent(undo1)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(undo2).addGap(117, 117, 117))
				.addGroup(layout.createSequentialGroup().addGap(48, 48, 48)
						.addComponent(leftPersceptive, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(60, 60, 60)
						.addComponent(mainImage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(66, 66, 66)
						.addComponent(rightPersceptive, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addContainerGap(44, Short.MAX_VALUE))
				.addGroup(
						GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(nameMainImage,
										GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
								.addGap(386, 386, 386)));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(61, 61, 61)
				.addComponent(nameMainImage, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(mainImage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(rightPersceptive, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(leftPersceptive, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(undo2).addComponent(undo1))
				.addContainerGap(114, Short.MAX_VALUE)));

		pack(); 
	}// </editor-fold>//GEN-END:initComponents

	private void undo1ActionPerformed(java.awt.event.ActionEvent evt) {
		// gestionnaireCommandes.undo();
	}

	private void undo2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CadrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CadrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CadrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CadrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CadrePrincipale().setVisible(true);
			}
		});
	}

}